### PR TITLE
fix #5

### LINKED ISSUE #5: File not found show ugly panic
If the solidity source is not found, the error is very ugly:

```
$ solang foo
thread 'main' panicked at 'file not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### PR DESCRIPTION
**Pull request by knarfytrebil**
Fixes the ugly panic message and gracefully quit when file does not exist.

### CODE REVIEW

File: src/bin/solang.rs [hunk 1]
```diff
@@ -130,7 +130,13 @@ fn process_filename(
 
     let mut json_contracts = HashMap::new();
 
-    let mut f = File::open(&filename).expect("file not found");
+    let mut f = match File::open(&filename) {
+        Err(err_info) => {
+            eprintln!("{}, {:?}", err_info.to_string(), &filename);
```
Comment (seanyoung) [inline src/bin/solang.rs]: The error should look similar to other errors and warnings. So, it should be something like: 
error: cannot open ‘foo.sol’: No such file or directory

Also your commit message should say what your are changing rather than just referencing an issue. Something like "improve error handling on file system errors"

Per hyperledger dco rules you need to have your real name in the commit message. You also have two signed-off-by lines in the commit message.

Looks very good thank you very much!

Comment (knarfytrebil) [reply src/bin/solang.rs]: Hi Sean, I have done the following as requested.
- Changed output message
- Changed commit message
- Signed with my real name
Have a nice day, cheers !

**Comment by seanyoung** [comment]
That looks perfect thank you very much!
